name: ci
on: push
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
          args: -c .golangci.yaml
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.15.x ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: Use cache dependencies
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: go mod download
    - name: Test
      run: go test ./...
